plugins:
  - stylelint-scss
  - stylelint-prettier
extends:
  - stylelint-config-standard
  - stylelint-config-standard-scss
  - stylelint-config-recess-order
  - stylelint-prettier/recommended
  - stylelint-config-prettier-scss
